[
  {
    trainNumber: 5,
    departureDate: "2021-05-09",
    operatorUICCode: 10,
    operatorShortCode: "vr",
    trainType: "IC",
    trainCategory: "Long-distance",
    commuterLineID: "",
    runningCurrently: true,
    cancelled: false,
    version: 278123154919,
    timetableType: "REGULAR",
    timetableAcceptanceDate: "2021-02-19T10:43:08.000Z",
    timeTableRows: [
      {
        stationShortCode: "HKI",
        stationUICCode: 1,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: true,
        commercialStop: true,
        commercialTrack: "8",
        cancelled: false,
        scheduledTime: "2021-05-09T10:19:00.000Z",
        actualTime: "2021-05-09T10:20:00.000Z",
        differenceInMinutes: 1,
        causes: [],
        trainReady: {
          source: "KUPLA",
          accepted: true,
          timestamp: "2021-05-09T10:14:17.000Z",
        },
      },
      {
        stationShortCode: "PSL",
        stationUICCode: 10,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: true,
        commercialStop: true,
        commercialTrack: "4",
        cancelled: false,
        scheduledTime: "2021-05-09T10:24:00.000Z",
        actualTime: "2021-05-09T10:24:29.000Z",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "PSL",
        stationUICCode: 10,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: true,
        commercialStop: true,
        commercialTrack: "4",
        cancelled: false,
        scheduledTime: "2021-05-09T10:25:00.000Z",
        actualTime: "2021-05-09T10:25:28.000Z",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "KÄP",
        stationUICCode: 977,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T10:27:00.000Z",
        actualTime: "2021-05-09T10:27:24.000Z",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "KÄP",
        stationUICCode: 977,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T10:27:00.000Z",
        actualTime: "2021-05-09T10:27:24.000Z",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "OLK",
        stationUICCode: 15,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T10:28:00.000Z",
        actualTime: "2021-05-09T10:28:04.000Z",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "OLK",
        stationUICCode: 15,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T10:28:00.000Z",
        actualTime: "2021-05-09T10:28:04.000Z",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "PMK",
        stationUICCode: 551,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T10:29:11.000Z",
        actualTime: "2021-05-09T10:28:54.000Z",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "PMK",
        stationUICCode: 551,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T10:29:11.000Z",
        actualTime: "2021-05-09T10:28:54.000Z",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "ML",
        stationUICCode: 17,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "2",
        cancelled: false,
        scheduledTime: "2021-05-09T10:30:00.000Z",
        actualTime: "2021-05-09T10:29:34.000Z",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "ML",
        stationUICCode: 17,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "2",
        cancelled: false,
        scheduledTime: "2021-05-09T10:30:00.000Z",
        actualTime: "2021-05-09T10:29:34.000Z",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "TNA",
        stationUICCode: 552,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T10:31:22.000Z",
        actualTime: "2021-05-09T10:30:02.000Z",
        differenceInMinutes: -1,
        causes: [],
      },
      {
        stationShortCode: "TNA",
        stationUICCode: 552,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T10:31:22.000Z",
        actualTime: "2021-05-09T10:30:02.000Z",
        differenceInMinutes: -1,
        causes: [],
      },
      {
        stationShortCode: "PLA",
        stationUICCode: 553,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T10:32:31.000Z",
        actualTime: "2021-05-09T10:30:56.000Z",
        differenceInMinutes: -2,
        causes: [],
      },
      {
        stationShortCode: "PLA",
        stationUICCode: 553,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T10:32:31.000Z",
        actualTime: "2021-05-09T10:30:56.000Z",
        differenceInMinutes: -2,
        causes: [],
      },
      {
        stationShortCode: "TKL",
        stationUICCode: 18,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: true,
        commercialStop: true,
        commercialTrack: "3",
        cancelled: false,
        scheduledTime: "2021-05-09T10:34:00.000Z",
        actualTime: "2021-05-09T10:32:38.000Z",
        differenceInMinutes: -1,
        causes: [],
      },
      {
        stationShortCode: "TKL",
        stationUICCode: 18,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: true,
        commercialStop: true,
        commercialTrack: "3",
        cancelled: false,
        scheduledTime: "2021-05-09T10:36:00.000Z",
        liveEstimateTime: "2021-05-09T10:36:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "HKH",
        stationUICCode: 556,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T10:36:40.000Z",
        liveEstimateTime: "2021-05-09T10:37:09.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "HKH",
        stationUICCode: 556,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T10:36:40.000Z",
        liveEstimateTime: "2021-05-09T10:37:09.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "HVK",
        stationUICCode: 1334,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T10:37:00.000Z",
        liveEstimateTime: "2021-05-09T10:37:26.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "HVK",
        stationUICCode: 1334,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T10:37:00.000Z",
        liveEstimateTime: "2021-05-09T10:37:26.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "KVY",
        stationUICCode: 559,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T10:37:56.000Z",
        liveEstimateTime: "2021-05-09T10:37:56.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "KVY",
        stationUICCode: 559,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T10:37:56.000Z",
        liveEstimateTime: "2021-05-09T10:37:56.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "RKL",
        stationUICCode: 554,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T10:38:34.000Z",
        liveEstimateTime: "2021-05-09T10:38:34.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "RKL",
        stationUICCode: 554,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T10:38:34.000Z",
        liveEstimateTime: "2021-05-09T10:38:34.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "HNA",
        stationUICCode: 1018,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T10:39:00.000Z",
        liveEstimateTime: "2021-05-09T10:39:04.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "HNA",
        stationUICCode: 1018,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T10:39:00.000Z",
        liveEstimateTime: "2021-05-09T10:39:04.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "KRS",
        stationUICCode: 19,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T10:39:31.000Z",
        liveEstimateTime: "2021-05-09T10:39:55.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "KRS",
        stationUICCode: 19,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T10:39:31.000Z",
        liveEstimateTime: "2021-05-09T10:39:55.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "SAV",
        stationUICCode: 555,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T10:40:58.000Z",
        liveEstimateTime: "2021-05-09T10:41:03.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "SAV",
        stationUICCode: 555,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T10:40:58.000Z",
        liveEstimateTime: "2021-05-09T10:41:03.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "KE",
        stationUICCode: 20,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T10:42:00.000Z",
        liveEstimateTime: "2021-05-09T10:42:02.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "KE",
        stationUICCode: 20,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T10:42:00.000Z",
        liveEstimateTime: "2021-05-09T10:42:02.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "KYT",
        stationUICCode: 1111,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T10:43:00.000Z",
        liveEstimateTime: "2021-05-09T10:43:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "KYT",
        stationUICCode: 1111,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T10:43:00.000Z",
        liveEstimateTime: "2021-05-09T10:43:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "HAA",
        stationUICCode: 13,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T10:46:30.000Z",
        liveEstimateTime: "2021-05-09T10:46:50.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "HAA",
        stationUICCode: 13,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T10:46:30.000Z",
        liveEstimateTime: "2021-05-09T10:46:50.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "KSU",
        stationUICCode: 1128,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T10:50:00.000Z",
        liveEstimateTime: "2021-05-09T10:50:20.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "KSU",
        stationUICCode: 1128,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T10:50:00.000Z",
        liveEstimateTime: "2021-05-09T10:50:20.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "MLÄ",
        stationUICCode: 27,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T10:53:00.000Z",
        liveEstimateTime: "2021-05-09T10:53:05.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "MLÄ",
        stationUICCode: 27,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T10:53:00.000Z",
        liveEstimateTime: "2021-05-09T10:53:05.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "SIP",
        stationUICCode: 1254,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T10:56:00.000Z",
        liveEstimateTime: "2021-05-09T10:56:04.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "SIP",
        stationUICCode: 1254,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T10:56:00.000Z",
        liveEstimateTime: "2021-05-09T10:56:04.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "HNN",
        stationUICCode: 1164,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T11:00:00.000Z",
        liveEstimateTime: "2021-05-09T11:00:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "HNN",
        stationUICCode: 1164,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T11:00:00.000Z",
        liveEstimateTime: "2021-05-09T11:00:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "HLT",
        stationUICCode: 1014,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T11:05:00.000Z",
        liveEstimateTime: "2021-05-09T11:05:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "HLT",
        stationUICCode: 1014,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T11:05:00.000Z",
        liveEstimateTime: "2021-05-09T11:05:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "LH",
        stationUICCode: 100,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: true,
        commercialStop: true,
        commercialTrack: "1",
        cancelled: false,
        scheduledTime: "2021-05-09T11:11:00.000Z",
        liveEstimateTime: "2021-05-09T11:11:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "LH",
        stationUICCode: 100,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: true,
        commercialStop: true,
        commercialTrack: "1",
        cancelled: false,
        scheduledTime: "2021-05-09T11:13:00.000Z",
        liveEstimateTime: "2021-05-09T11:13:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "VLH",
        stationUICCode: 104,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T11:18:00.000Z",
        liveEstimateTime: "2021-05-09T11:18:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "VLH",
        stationUICCode: 104,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T11:18:00.000Z",
        liveEstimateTime: "2021-05-09T11:18:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "NSL",
        stationUICCode: 595,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T11:20:00.000Z",
        liveEstimateTime: "2021-05-09T11:20:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "NSL",
        stationUICCode: 595,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T11:20:00.000Z",
        liveEstimateTime: "2021-05-09T11:20:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "UKÄ",
        stationUICCode: 105,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T11:21:30.000Z",
        liveEstimateTime: "2021-05-09T11:21:30.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "UKÄ",
        stationUICCode: 105,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T11:21:30.000Z",
        liveEstimateTime: "2021-05-09T11:21:30.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "MKA",
        stationUICCode: 1336,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T11:25:30.000Z",
        liveEstimateTime: "2021-05-09T11:25:45.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "MKA",
        stationUICCode: 1336,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T11:25:30.000Z",
        liveEstimateTime: "2021-05-09T11:25:45.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "KA",
        stationUICCode: 477,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T11:29:00.000Z",
        liveEstimateTime: "2021-05-09T11:29:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "KA",
        stationUICCode: 477,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T11:29:00.000Z",
        liveEstimateTime: "2021-05-09T11:29:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "NMÄ",
        stationUICCode: 1324,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T11:30:00.000Z",
        liveEstimateTime: "2021-05-09T11:30:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "NMÄ",
        stationUICCode: 1324,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T11:30:00.000Z",
        liveEstimateTime: "2021-05-09T11:30:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "SMÄ",
        stationUICCode: 1325,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T11:33:00.000Z",
        liveEstimateTime: "2021-05-09T11:33:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "SMÄ",
        stationUICCode: 1325,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T11:33:00.000Z",
        liveEstimateTime: "2021-05-09T11:33:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "KRA",
        stationUICCode: 478,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T11:36:00.000Z",
        liveEstimateTime: "2021-05-09T11:36:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "KRA",
        stationUICCode: 478,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T11:36:00.000Z",
        liveEstimateTime: "2021-05-09T11:36:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "KV",
        stationUICCode: 480,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: true,
        commercialStop: true,
        commercialTrack: "7",
        cancelled: false,
        scheduledTime: "2021-05-09T11:41:00.000Z",
        liveEstimateTime: "2021-05-09T11:41:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "KV",
        stationUICCode: 480,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: true,
        commercialStop: true,
        commercialTrack: "7",
        cancelled: false,
        scheduledTime: "2021-05-09T11:43:00.000Z",
        liveEstimateTime: "2021-05-09T11:43:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "KUV",
        stationUICCode: 1320,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T11:47:00.000Z",
        liveEstimateTime: "2021-05-09T11:47:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "KUV",
        stationUICCode: 1320,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T11:47:00.000Z",
        liveEstimateTime: "2021-05-09T11:47:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "UTI",
        stationUICCode: 484,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T11:50:00.000Z",
        liveEstimateTime: "2021-05-09T11:50:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "UTI",
        stationUICCode: 484,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T11:50:00.000Z",
        liveEstimateTime: "2021-05-09T11:50:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "KTH",
        stationUICCode: 1319,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T11:51:00.000Z",
        liveEstimateTime: "2021-05-09T11:51:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "KTH",
        stationUICCode: 1319,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T11:51:00.000Z",
        liveEstimateTime: "2021-05-09T11:51:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "KPA",
        stationUICCode: 485,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T11:54:00.000Z",
        liveEstimateTime: "2021-05-09T11:54:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "KPA",
        stationUICCode: 485,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T11:54:00.000Z",
        liveEstimateTime: "2021-05-09T11:54:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "KJR",
        stationUICCode: 944,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T11:58:00.000Z",
        liveEstimateTime: "2021-05-09T11:58:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "KJR",
        stationUICCode: 944,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T11:58:00.000Z",
        liveEstimateTime: "2021-05-09T11:58:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "TA",
        stationUICCode: 486,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T12:02:00.000Z",
        liveEstimateTime: "2021-05-09T12:02:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "TA",
        stationUICCode: 486,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T12:02:00.000Z",
        liveEstimateTime: "2021-05-09T12:02:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "LÄ",
        stationUICCode: 487,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T12:06:00.000Z",
        liveEstimateTime: "2021-05-09T12:07:06.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 1,
        causes: [],
      },
      {
        stationShortCode: "LÄ",
        stationUICCode: 487,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T12:06:00.000Z",
        liveEstimateTime: "2021-05-09T12:07:06.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 1,
        causes: [],
      },
      {
        stationShortCode: "RAS",
        stationUICCode: 1222,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T12:10:00.000Z",
        liveEstimateTime: "2021-05-09T12:10:22.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "RAS",
        stationUICCode: 1222,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T12:10:00.000Z",
        liveEstimateTime: "2021-05-09T12:10:22.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "TRÄ",
        stationUICCode: 1290,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T12:13:00.000Z",
        liveEstimateTime: "2021-05-09T12:13:08.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "TRÄ",
        stationUICCode: 1290,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T12:13:00.000Z",
        liveEstimateTime: "2021-05-09T12:13:08.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "TAP",
        stationUICCode: 1276,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T12:16:00.000Z",
        liveEstimateTime: "2021-05-09T12:16:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "TAP",
        stationUICCode: 1276,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T12:16:00.000Z",
        liveEstimateTime: "2021-05-09T12:16:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "LR",
        stationUICCode: 495,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: true,
        commercialStop: true,
        commercialTrack: "1",
        cancelled: false,
        scheduledTime: "2021-05-09T12:21:00.000Z",
        liveEstimateTime: "2021-05-09T12:21:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "LR",
        stationUICCode: 495,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: true,
        commercialStop: true,
        commercialTrack: "1",
        cancelled: false,
        scheduledTime: "2021-05-09T12:23:00.000Z",
        liveEstimateTime: "2021-05-09T12:23:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "LRS",
        stationUICCode: 498,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T12:27:00.000Z",
        liveEstimateTime: "2021-05-09T12:27:56.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "LRS",
        stationUICCode: 498,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T12:27:00.000Z",
        liveEstimateTime: "2021-05-09T12:27:56.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "MKO",
        stationUICCode: 1180,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T12:32:00.000Z",
        liveEstimateTime: "2021-05-09T12:32:33.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "MKO",
        stationUICCode: 1180,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T12:32:00.000Z",
        liveEstimateTime: "2021-05-09T12:32:33.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "JTS",
        stationUICCode: 499,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: true,
        commercialStop: true,
        commercialTrack: "1",
        cancelled: false,
        scheduledTime: "2021-05-09T12:38:00.000Z",
        liveEstimateTime: "2021-05-09T12:38:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "JTS",
        stationUICCode: 499,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: true,
        commercialStop: true,
        commercialTrack: "1",
        cancelled: false,
        scheduledTime: "2021-05-09T12:39:00.000Z",
        liveEstimateTime: "2021-05-09T12:39:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "RAH",
        stationUICCode: 501,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T12:47:00.000Z",
        liveEstimateTime: "2021-05-09T12:47:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "RAH",
        stationUICCode: 501,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T12:47:00.000Z",
        liveEstimateTime: "2021-05-09T12:47:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "IMR",
        stationUICCode: 603,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: true,
        commercialStop: true,
        commercialTrack: "1",
        cancelled: false,
        scheduledTime: "2021-05-09T12:52:00.000Z",
        liveEstimateTime: "2021-05-09T12:52:25.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "IMR",
        stationUICCode: 603,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: true,
        commercialStop: true,
        commercialTrack: "1",
        cancelled: false,
        scheduledTime: "2021-05-09T12:54:00.000Z",
        liveEstimateTime: "2021-05-09T12:54:25.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "IMT",
        stationUICCode: 502,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T12:57:00.000Z",
        liveEstimateTime: "2021-05-09T12:57:21.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "IMT",
        stationUICCode: 502,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T12:57:00.000Z",
        liveEstimateTime: "2021-05-09T12:57:21.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "IM",
        stationUICCode: 1352,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T13:00:32.000Z",
        liveEstimateTime: "2021-05-09T13:00:53.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "IM",
        stationUICCode: 1352,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T13:00:32.000Z",
        liveEstimateTime: "2021-05-09T13:00:53.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "RJÄ",
        stationUICCode: 506,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T13:08:00.000Z",
        liveEstimateTime: "2021-05-09T13:08:21.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "RJÄ",
        stationUICCode: 506,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T13:08:00.000Z",
        liveEstimateTime: "2021-05-09T13:08:21.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "SPL",
        stationUICCode: 507,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T13:19:00.000Z",
        liveEstimateTime: "2021-05-09T13:19:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "SPL",
        stationUICCode: 507,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T13:19:00.000Z",
        liveEstimateTime: "2021-05-09T13:19:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "KIJ",
        stationUICCode: 1123,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T13:29:11.000Z",
        liveEstimateTime: "2021-05-09T13:29:11.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "KIJ",
        stationUICCode: 1123,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T13:29:11.000Z",
        liveEstimateTime: "2021-05-09T13:29:11.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "PAR",
        stationUICCode: 510,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: true,
        commercialStop: true,
        commercialTrack: "1",
        cancelled: false,
        scheduledTime: "2021-05-09T13:31:00.000Z",
        liveEstimateTime: "2021-05-09T13:31:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "PAR",
        stationUICCode: 510,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: true,
        commercialStop: true,
        commercialTrack: "1",
        cancelled: false,
        scheduledTime: "2021-05-09T13:33:00.000Z",
        liveEstimateTime: "2021-05-09T13:33:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "SR",
        stationUICCode: 964,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T13:43:00.000Z",
        liveEstimateTime: "2021-05-09T13:43:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "SR",
        stationUICCode: 964,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T13:43:00.000Z",
        liveEstimateTime: "2021-05-09T13:43:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "POI",
        stationUICCode: 965,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T13:48:33.000Z",
        liveEstimateTime: "2021-05-09T13:48:33.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "POI",
        stationUICCode: 965,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T13:48:33.000Z",
        liveEstimateTime: "2021-05-09T13:48:33.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "KTI",
        stationUICCode: 966,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: true,
        commercialStop: true,
        commercialTrack: "1",
        cancelled: false,
        scheduledTime: "2021-05-09T13:54:00.000Z",
        liveEstimateTime: "2021-05-09T13:54:05.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "KTI",
        stationUICCode: 966,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: true,
        commercialStop: true,
        commercialTrack: "1",
        cancelled: false,
        scheduledTime: "2021-05-09T13:55:00.000Z",
        liveEstimateTime: "2021-05-09T13:55:05.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "PUS",
        stationUICCode: 919,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T14:09:00.000Z",
        liveEstimateTime: "2021-05-09T14:09:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "PUS",
        stationUICCode: 919,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T14:09:00.000Z",
        liveEstimateTime: "2021-05-09T14:09:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "KIT",
        stationUICCode: 453,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: true,
        commercialStop: true,
        commercialTrack: "1",
        cancelled: false,
        scheduledTime: "2021-05-09T14:13:00.000Z",
        liveEstimateTime: "2021-05-09T14:13:15.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "KIT",
        stationUICCode: 453,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: true,
        commercialStop: true,
        commercialTrack: "1",
        cancelled: false,
        scheduledTime: "2021-05-09T14:14:00.000Z",
        liveEstimateTime: "2021-05-09T14:14:15.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "SÄ",
        stationUICCode: 918,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T14:25:00.000Z",
        liveEstimateTime: "2021-05-09T14:25:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "SÄ",
        stationUICCode: 918,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T14:25:00.000Z",
        liveEstimateTime: "2021-05-09T14:25:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "TKK",
        stationUICCode: 916,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T14:28:00.000Z",
        liveEstimateTime: "2021-05-09T14:28:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "TKK",
        stationUICCode: 916,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T14:28:00.000Z",
        liveEstimateTime: "2021-05-09T14:28:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "HSL",
        stationUICCode: 451,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T14:34:00.000Z",
        liveEstimateTime: "2021-05-09T14:34:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "HSL",
        stationUICCode: 451,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T14:34:00.000Z",
        liveEstimateTime: "2021-05-09T14:34:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "NTH",
        stationUICCode: 917,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T14:40:00.000Z",
        liveEstimateTime: "2021-05-09T14:40:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "NTH",
        stationUICCode: 917,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T14:40:00.000Z",
        liveEstimateTime: "2021-05-09T14:40:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "SUL",
        stationUICCode: 1071,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T14:47:37.000Z",
        liveEstimateTime: "2021-05-09T14:47:37.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "SUL",
        stationUICCode: 1071,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T14:47:37.000Z",
        liveEstimateTime: "2021-05-09T14:47:37.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "PLT",
        stationUICCode: 1070,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T14:48:21.000Z",
        liveEstimateTime: "2021-05-09T14:48:21.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "PLT",
        stationUICCode: 1070,
        countryCode: "FI",
        type: "DEPARTURE",
        trainStopping: false,
        commercialTrack: "",
        cancelled: false,
        scheduledTime: "2021-05-09T14:48:21.000Z",
        liveEstimateTime: "2021-05-09T14:48:21.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
      {
        stationShortCode: "JNS",
        stationUICCode: 460,
        countryCode: "FI",
        type: "ARRIVAL",
        trainStopping: true,
        commercialStop: true,
        commercialTrack: "3",
        cancelled: false,
        scheduledTime: "2021-05-09T14:49:00.000Z",
        liveEstimateTime: "2021-05-09T14:49:00.000Z",
        estimateSource: "COMBOCALC",
        differenceInMinutes: 0,
        causes: [],
      },
    ],
  },
];
